// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type DeploymentConfig = { 
/**
 * SQS standard queue ARN for the shared events stream. All Lambda
 * wrappers in the deployment emit invocation events here.
 */
eventsQueueArn?: string | null, };
