// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentName } from "./DeploymentName.ts";
import type { FunctionName } from "./FunctionName.ts";
import type { LookupManifest } from "./LookupManifest.ts";
import type { RunId } from "./RunId.ts";
import type { JsonValue } from "./serde_json/JsonValue.ts";

export type DriverArgs = { runId: RunId, deploymentName: DeploymentName, deploymentPath: string, entryPoint: FunctionName, input: JsonValue, params: JsonValue, lookupManifest: LookupManifest, };
