// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvocationEvent } from "./InvocationEvent.ts";
import type { LogEvent } from "./LogEvent.ts";

export type DriverEvent = { "type": "log" } & LogEvent | InvocationEvent;
