// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InvocationFailureEvent } from "./InvocationFailureEvent.ts";
import type { InvocationSuccessEvent } from "./InvocationSuccessEvent.ts";

export type InvocationEvent = { "type": "invocationSuccess" } & InvocationSuccessEvent | { "type": "invocationFailure" } & InvocationFailureEvent;
