// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionName } from "./FunctionName.ts";
import type { InvocationId } from "./InvocationId.ts";
import type { JsonValue } from "./serde_json/JsonValue.ts";

export type InvocationFailureEvent = { id: InvocationId, parent: InvocationId | null, predecessor: InvocationId | null, functionName: FunctionName, input: JsonValue, params: JsonValue, startTime: string, error: JsonValue | null, };
