// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionName } from "./FunctionName.ts";
import type { InvocationId } from "./InvocationId.ts";
import type { LogLevel } from "./LogLevel.ts";
import type { JsonValue } from "./serde_json/JsonValue.ts";

export type InvocationLogMessage = { level: LogLevel, message: string, data: JsonValue | null, invocationId: InvocationId, functionName: FunctionName, };
