// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FunctionName } from "./FunctionName.ts";
import type { LookupEntryKind } from "./LookupEntryKind.ts";

export type LookupEntry = { name: FunctionName, kind: LookupEntryKind, 
/**
 * Lambda ARN (AWS) or HTTP URL (Knative).
 */
location: string, 
/**
 * SQS Standard invoke queue URL. AWS functions only.
 */
invokeQueueUrl?: string | null, };
