// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LookupEntry } from "./LookupEntry.ts";

export type LookupManifest = { 
/**
 * URL of the shared SQS events queue for this deployment.
 * All Lambda wrappers emit observability events here.
 */
eventsQueueUrl: string, entries: Array<LookupEntry>, };
