// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LogLevel } from "./LogLevel.ts";
import type { JsonValue } from "./serde_json/JsonValue.ts";

export type WorkflowLogMessage = { level: LogLevel, message: string, data: JsonValue | null, };
